In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

In [2]:
df = pd.read_csv('C:/Users/jhonn/Downloads/data_jobs.csv')
df.head(2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."

In [3]:
#Cleanind the date 
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [6]:
#Filling with median
df.loc[:10,'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [8]:
median_salary_year = df['salary_year_avg'].median()

In [9]:
median_salary_hour = df['salary_hour_avg'].median()

In [10]:
df_filled = df

In [12]:
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)

In [11]:
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [13]:
df_filled.loc[:10,'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [15]:
df_unique = df_filled
df_unique = df_unique.drop_duplicates()

len(df_filled)-len(df_unique)

101

In [16]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])
len(df_filled)-len(df_unique)

277699