# SAMPLE and COPY

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

df = pd.read_csv('C:/Users/jhonn/Downloads/data_jobs.csv')

#Cleaning the date 
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df = pd.read_csv('C:/Users/jhonn/Downloads/data_jobs.csv')
df.head(2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."

In [ ]:
# a sample of the DF

df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
614247,Data Engineer,Lead Data Engineer,"Nashville, TN",via Dice,Full-time,False,Sudan,2023-08-18 12:41:21,True,False,Sudan,NaN,NaN,NaN,TEKsystems c/o Allegis Group,"['sql', 'python', 'aws', 'redshift', 'aurora',...","{'cloud': ['aws', 'redshift', 'aurora'], 'libr..."
469233,Data Analyst,Junior/Medior Data Analyst HR,"Amsterdam, Netherlands",via Nationale Vacaturebank,Full-time,False,Netherlands,2023-04-04 14:43:59,True,False,Netherlands,NaN,NaN,NaN,Qualogy,['azure'],{'cloud': ['azure']}
41267,Data Analyst,Information Security Advisor - Data Discovery ...,"Atlanta, GA",via LinkedIn,Full-time,False,Georgia,2023-06-25 07:06:21,False,True,United States,NaN,NaN,NaN,Elevance Health,"['aws', 'gcp', 'azure']","{'cloud': ['aws', 'gcp', 'azure']}"
140169,Data Analyst,Data Analyst Financial Services,"Miami, FL",via BeBee,Full-time,False,"Florida, United States",2023-11-21 08:02:26,True,True,United States,NaN,NaN,NaN,dv01,"['r', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
422300,Data Analyst,Data Analyst,"Hartford, CT",via Monster,Full-time,False,"New York, United States",2023-01-04 16:00:10,True,True,United States,NaN,NaN,NaN,Creative Financial Staffing,"['sql', 'python', 'vba', 'power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
687106,Data Scientist,Data Scientist (4500 USD/Mes) [Remote],Anywhere,via LinkedIn,Full-time,True,Chile,2023-12-13 11:14:12,False,False,Chile,NaN,NaN,NaN,Listopro,"['sql', 'python', 'r', 'bigquery', 'redshift']","{'cloud': ['bigquery', 'redshift'], 'programmi..."
424000,Data Analyst,data quality analyst - los angeles,"Los Angeles, CA",via Nexxt,Contractor,False,"California, United States",2023-07-06 16:01:05,False,False,United States,NaN,NaN,NaN,Randstad US,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
705773,Data Analyst,Data Analyst,"Taguig, Metro Manila, Philippines",via Indeed,Full-time and Temp work,False,Philippines,2023-10-12 03:12:53,False,False,Philippines,NaN,NaN,NaN,SL Temps Incorporated,"['vba', 'excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
724198,Data Engineer,Data Engineer - Remote,Illinois,via Dice,Full-time,False,"Texas, United States",2023-09-05 21:06:45,False,False,United States,NaN,NaN,NaN,"ConsultNet, LLC","['sql', 'python', 'aws']","{'cloud': ['aws'], 'programming': ['sql', 'pyt..."
756131,Data Scientist,Data Science (AI/Machine Learning & NLP) Inter...,"Visakhapatnam, Andhra Pradesh, India (+2 others)",via Internshala,Full-time,False,India,2023-02-26 20:08:12,False,False,India,NaN,NaN,NaN,Educareit,"['r', 'mongodb', 'mongodb', 'nosql', 'python',...","{'cloud': ['aws'], 'databases': ['mongodb', 'e..."

In [6]:
df.sample(10, random_state=(42))

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,NaN,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,NaN,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,NaN,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,NaN,NaN,NaN,KPMG France,NaN,NaN
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,NaN,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [7]:
# use the copy method because operations could affect the original dataset. That's not what u want


df_alteredna = df.copy()

In [8]:
id(df_alteredna) == id(df)

False